/* ===== ER Diagram Tool ===== */
class ERDiagramTool {
  constructor() {
    this.entities = [];
    this.relations = [];
    this.entityIdCounter = 0;
    this.selectedEntity = null;
    this.undoHistory = [];
    this.isApplyingUndo = false;
    this.viewMode = 'logical'; // 'logical' or 'physical'
    this.sqlDialect = 'mysql'; // 'mysql' or 'postgres'
    this.canvas = document.getElementById('er-canvas');
    this.svg = document.getElementById('er-svg');
    this.connectingFrom = null;
    this.initActionButtons();
    // Add sample entities
    this.addEntityAt('ユーザー', 'users', [
      {logicalName:'ユーザーID', physicalName:'user_id', type:'INT', pk:true, fk:false},
      {logicalName:'氏名', physicalName:'name', type:'VARCHAR', pk:false, fk:false},
      {logicalName:'メールアドレス', physicalName:'email', type:'VARCHAR', pk:false, fk:false},
      {logicalName:'登録日時', physicalName:'created_at', type:'DATETIME', pk:false, fk:false}
    ], 100, 80);
    this.addEntityAt('注文', 'orders', [
      {logicalName:'注文ID', physicalName:'order_id', type:'INT', pk:true, fk:false},
      {logicalName:'ユーザーID', physicalName:'user_id', type:'INT', pk:false, fk:true},
      {logicalName:'合計金額', physicalName:'total', type:'DECIMAL', pk:false, fk:false},
      {logicalName:'ステータス', physicalName:'status', type:'VARCHAR', pk:false, fk:false},
      {logicalName:'注文日時', physicalName:'ordered_at', type:'DATETIME', pk:false, fk:false}
    ], 420, 80);
    this.addEntityAt('商品', 'products', [
      {logicalName:'商品ID', physicalName:'product_id', type:'INT', pk:true, fk:false},
      {logicalName:'商品名', physicalName:'name', type:'VARCHAR', pk:false, fk:false},
      {logicalName:'価格', physicalName:'price', type:'DECIMAL', pk:false, fk:false},
      {logicalName:'在庫数', physicalName:'stock', type:'INT', pk:false, fk:false}
    ], 420, 340);
    this.relations.push({from:this.entities[1].id,to:this.entities[0].id,label:'1:N'});
    this.relations.push({from:this.entities[1].id,to:this.entities[2].id,label:'N:M'});
    this.drawRelations();

    // キャンバスのクリックで選択解除および接続モードキャンセル
    this.canvas.addEventListener('mousedown', (e) => {
      if (e.target === this.canvas || e.target === this.svg) {
        if (this.connectingFrom) {
          this.connectingFrom = null;
          showToast('接続モードをキャンセルしました');
        }
        this.canvas.querySelectorAll('.er-entity').forEach(el => el.classList.remove('selected'));
        this.selectedEntity = null;
      }
    });
  }

  initActionButtons() {
    const section = this.canvas.closest('.tool-section');
    if (section) {
      section.querySelectorAll('[data-action]').forEach(btn => {
        btn.addEventListener('click', () => {
          const action = btn.dataset.action;
          if (typeof this[action] === 'function') {
            this[action]();
          } else {
            console.warn(`Action "${action}" not implemented in ERDiagramTool`);
          }
        });
      });
      if (window.lucide) {
        lucide.createIcons({ root: section });
      }
    }
  }

  redoLastAction() { showToast('やり直し機能は未実装です'); }
  autoLayout() { showToast('自動レイアウトは未実装です'); }
  save() { showToast('ブラウザのローカルストレージに保存しました'); }
  copy() { if(this.selectedEntity) showToast('エンティティをコピーしました'); }
  paste() { showToast('貼り付けは未実装です'); }

  toggleSidebar() {
    document.body.classList.toggle('sidebar-collapsed');
  }

  toggleNameView() {
    this.viewMode = this.viewMode === 'logical' ? 'physical' : 'logical';
    const btn = document.getElementById('er-toggle-name-btn');
    if (btn) btn.textContent = this.viewMode === 'logical' ? '🌐 論理名を表示中' : '💻 物理名を表示中';
    this.entities.forEach(entity => {
      const el = document.getElementById(entity.id);
      if (el) {
        el.querySelector('.er-entity-header').textContent = this.viewMode === 'logical' ? entity.logicalName : entity.physicalName;
        el.querySelector('.er-entity-attrs').innerHTML = entity.attrs.map(a => `<div class="er-attr">
          ${a.pk?'<span class="attr-key">PK</span>':''}${a.fk?'<span class="attr-key" style="color:#06b6d4">FK</span>':''}
          <span>${this.escapeHtml(this.viewMode === 'logical' ? a.logicalName : a.physicalName)}</span><span class="attr-type">${a.type}</span>
        </div>`).join('');
      }
    });
  }

  exportSQL() {
    const isPG = this.sqlDialect === 'postgres';
    const quote = isPG ? '"' : '`';
    let sql = `-- DDL Export generated by UpStream (${this.sqlDialect.toUpperCase()})\n\n`;

    this.entities.forEach(entity => {
      sql += `CREATE TABLE ${quote}${entity.physicalName}${quote} (\n`;
      const colDefs = [];
      const pks = [];
      
      entity.attrs.forEach(attr => {
        let type = attr.type;
        if (isPG) {
          if (type === 'INT') type = 'INTEGER';
          if (type === 'DATETIME') type = 'TIMESTAMP';
          if (attr.pk && (type === 'INTEGER' || type === 'INT')) type = 'SERIAL';
        }
        
        let col = `  ${quote}${attr.physicalName}${quote} ${type}`;
        colDefs.push(col);
        if (attr.pk) pks.push(`${quote}${attr.physicalName}${quote}`);
      });
      
      if (pks.length > 0) {
        colDefs.push(`  PRIMARY KEY (${pks.join(', ')})`);
      }
      
      sql += colDefs.join(',\n') + '\n';
      
      if (isPG) {
        sql += `);\n`;
        sql += `COMMENT ON TABLE "${entity.physicalName}" IS '${entity.logicalName}';\n`;
        entity.attrs.forEach(attr => {
          sql += `COMMENT ON COLUMN "${entity.physicalName}"."${attr.physicalName}" IS '${attr.logicalName}';\n`;
        });
        sql += `\n`;
      } else {
        sql += `) COMMENT='${entity.logicalName}';\n\n`;
      }
    });
    
    const modal = document.createElement('div');
    modal.className = 'modal-overlay';
    modal.innerHTML = `
      <div class="modal er-class-modal" style="min-width: 600px;">
        <h2>DDL出力 (${this.sqlDialect === 'mysql' ? 'MySQL' : 'PostgreSQL'})</h2>
        <textarea class="form-input" style="height: 300px; font-family: monospace; resize: vertical;" readonly>${this.escapeHtml(sql)}</textarea>
        <div class="modal-actions" style="margin-top: 16px;">
          <button class="btn btn-primary" onclick="this.closest('.modal-overlay').remove()">閉じる</button>
        </div>
      </div>
    `;
    document.body.appendChild(modal);
  }

  addEntityAt(logicalName, physicalName, attrs, x, y) {
    const id = 'er_entity_' + (this.entityIdCounter++);
    const entity = { id, logicalName, physicalName, attrs, x, y };
    this.entities.push(entity);
    this.renderEntity(entity);
    this.pushUndoAction({
      type: 'removeEntity',
      entityId: entity.id,
      entityIndex: this.entities.length - 1,
      entityIdCounter: this.entityIdCounter - 1,
    });
    return entity;
  }
  addEntity() {
    this.showEntityForm();
  }

  showEntityForm(existingEntity = null) {
    const isEdit = !!existingEntity;
    const title = isEdit ? 'エンティティを編集' : 'エンティティを追加';
    const logicalName = isEdit ? existingEntity.logicalName : '';
    const physicalName = isEdit ? existingEntity.physicalName : '';
    const initialAttrs = isEdit ? existingEntity.attrs : [
      { logicalName: 'ID', physicalName: 'id', type: 'INT', pk: true, fk: false }
    ];

    const container = document.getElementById('modal-container');
    if (!container) return;

    container.innerHTML = `
      <div class="modal-overlay">
        <div class="modal er-class-modal" style="min-width: 600px;">
          <h2>${title}</h2>
          <div class="form-group" style="display:flex; gap:10px;">
            <div style="flex:1;">
              <label>論理名 (日本語等)</label>
              <input type="text" class="form-input" id="er-form-logical-name" value="${this.escapeHtml(logicalName)}" placeholder="例: ユーザー" autofocus>
            </div>
            <div style="flex:1;">
              <label>物理名 (英数字)</label>
              <input type="text" class="form-input" id="er-form-physical-name" value="${this.escapeHtml(physicalName)}" placeholder="例: users">
            </div>
          </div>
          <div class="form-group">
            <label>カラム定義</label>
            <div class="er-form-rows" id="er-form-rows-container"></div>
            <button type="button" class="btn btn-sm btn-secondary er-form-add-btn" id="er-form-add-row">＋ カラムを追加</button>
          </div>
          <div class="modal-actions">
            <button class="btn btn-secondary" onclick="document.getElementById('modal-container').innerHTML=''">キャンセル</button>
            <button class="btn btn-primary" id="er-form-submit">${isEdit ? '更新' : '作成'}</button>
          </div>
        </div>
      </div>
    `;

    const rowsContainer = document.getElementById('er-form-rows-container');
    const addRowBtn = document.getElementById('er-form-add-row');
    const submitBtn = document.getElementById('er-form-submit');

    const createRow = (attr = { logicalName: '', physicalName: '', type: 'VARCHAR', pk: false, fk: false }) => {
      const row = document.createElement('div');
      row.className = 'er-form-row';
      row.innerHTML = `
        <button type="button" class="er-form-key-btn pk ${attr.pk ? 'active' : ''}" title="Primary Key">PK</button>
        <button type="button" class="er-form-key-btn fk ${attr.fk ? 'active' : ''}" title="Foreign Key">FK</button>
        <input type="text" class="form-input er-form-logical-input" placeholder="論理名" value="${this.escapeHtml(attr.logicalName)}" style="flex:1;">
        <input type="text" class="form-input er-form-physical-input" placeholder="物理名" value="${this.escapeHtml(attr.physicalName)}" style="flex:1;">
        <select class="form-input er-form-type-select" style="flex:0.8;">
          ${['INT', 'BIGINT', 'VARCHAR', 'TEXT', 'BOOLEAN', 'DATE', 'DATETIME', 'DECIMAL', 'JSON', 'UUID'].map(t => 
            `<option value="${t}" ${attr.type === t ? 'selected' : ''}>${t}</option>`
          ).join('')}
        </select>
        <button type="button" class="er-form-del-btn" title="削除">✕</button>
      `;

      // PK Toggle
      row.querySelector('.pk').addEventListener('click', (e) => e.target.classList.toggle('active'));
      // FK Toggle
      row.querySelector('.fk').addEventListener('click', (e) => e.target.classList.toggle('active'));
      // Delete
      row.querySelector('.er-form-del-btn').addEventListener('click', () => row.remove());

      rowsContainer.appendChild(row);
    };

    initialAttrs.forEach(createRow);

    addRowBtn.addEventListener('click', () => createRow());

    submitBtn.addEventListener('click', () => {
      const logName = document.getElementById('er-form-logical-name').value.trim();
      const phyName = document.getElementById('er-form-physical-name').value.trim();
      if (!logName || !phyName) { showToast('論理名と物理名を入力してください'); return; }

      const rows = rowsContainer.querySelectorAll('.er-form-row');
      const attrs = Array.from(rows).map(row => ({
        logicalName: row.querySelector('.er-form-logical-input').value.trim() || 'カラム',
        physicalName: row.querySelector('.er-form-physical-input').value.trim() || 'column',
        type: row.querySelector('.er-form-type-select').value,
        pk: row.querySelector('.pk').classList.contains('active'),
        fk: row.querySelector('.fk').classList.contains('active')
      }));

      if (isEdit) {
        const oldState = { 
          logicalName: existingEntity.logicalName, 
          physicalName: existingEntity.physicalName, 
          attrs: JSON.parse(JSON.stringify(existingEntity.attrs)) 
        };
        existingEntity.logicalName = logName;
        existingEntity.physicalName = phyName;
        existingEntity.attrs = attrs;
        
        this.pushUndoAction({
          type: 'updateEntity',
          entityId: existingEntity.id,
          oldState: oldState
        });

        const el = document.getElementById(existingEntity.id);
        if (el) {
          el.querySelector('.er-entity-header').textContent = this.viewMode === 'logical' ? logName : phyName;
          el.querySelector('.er-entity-attrs').innerHTML = attrs.map(a => `<div class="er-attr">
            ${a.pk?'<span class="attr-key">PK</span>':''}${a.fk?'<span class="attr-key" style="color:#06b6d4">FK</span>':''}
            <span>${this.escapeHtml(this.viewMode === 'logical' ? a.logicalName : a.physicalName)}</span><span class="attr-type">${a.type}</span>
          </div>`).join('');
        }
        showToast('エンティティを更新しました');
      } else {
        const offset = this.entities.length * 30;
        this.addEntityAt(logName, phyName, attrs, 100 + offset, 100 + offset);
        showToast('エンティティを追加しました');
      }

      container.innerHTML = '';
    });
  }

  escapeHtml(str) {
    if (!str) return '';
    return str.replace(/[&<>"']/g, m => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    })[m]);
  }
  renderEntity(entity) {
    const el = document.createElement('div');
    el.className = 'er-entity';
    el.id = entity.id;
    el.style.left = entity.x + 'px';
    el.style.top = entity.y + 'px';
    el.innerHTML = `
      <div class="er-entity-header">${this.viewMode === 'logical' ? entity.logicalName : entity.physicalName}</div>
      <div class="er-entity-attrs">
        ${entity.attrs.map(a => `<div class="er-attr">
          ${a.pk?'<span class="attr-key">PK</span>':''}${a.fk?'<span class="attr-key" style="color:#06b6d4">FK</span>':''}
          <span>${this.escapeHtml(this.viewMode === 'logical' ? a.logicalName : a.physicalName)}</span><span class="attr-type">${a.type}</span>
        </div>`).join('')}
      </div>`;
    let dragging = false, ox, oy;
    el.addEventListener('mousedown', e => {
      if (this.connectingFrom) {
        if (this.connectingFrom.id !== entity.id) {
          const label = prompt('リレーション (例: 1:N, N:M) [空でキャンセル]:', '1:N');
          if (label === null || label.trim() === '') {
            this.connectingFrom = null;
            document.querySelectorAll('.er-entity').forEach(el => el.classList.remove('selected'));
            return;
          }

          // 外部キーの自動追加
          if (label.includes('N') || label.includes('M') || label.includes('1:1')) {
             const parent = this.getEntityById(this.connectingFrom.id);
             if (parent) {
                const pk = parent.attrs.find(a => a.pk);
                if (pk) {
                   const fkLogicalName = parent.logicalName + 'ID';
                   const fkPhysicalName = parent.physicalName.replace(/s$/, '') + '_id';
                   if (!entity.attrs.find(a => a.physicalName === fkPhysicalName)) {
                      entity.attrs.push({
                         logicalName: fkLogicalName,
                         physicalName: fkPhysicalName,
                         type: pk.type,
                         pk: false,
                         fk: true
                      });
                      el.querySelector('.er-entity-attrs').innerHTML = entity.attrs.map(a => `<div class="er-attr">
                        ${a.pk?'<span class="attr-key">PK</span>':''}${a.fk?'<span class="attr-key" style="color:#06b6d4">FK</span>':''}
                        <span>${this.escapeHtml(this.viewMode === 'logical' ? a.logicalName : a.physicalName)}</span><span class="attr-type">${a.type}</span>
                      </div>`).join('');
                      showToast(`外部キー ${fkPhysicalName} を自動追加しました`);
                   }
                }
             }
          }

          this.relations.push({from: this.connectingFrom.id, to: entity.id, label});
          this.drawRelations();
          document.getElementById(this.connectingFrom.id)?.classList.remove('selected');
          this.pushUndoAction({
            type: 'removeRelation',
            from: this.connectingFrom.id,
            to: entity.id,
            label,
          });
          this.connectingFrom = null;
        }
        return;
      }
      dragging = true;
      this.selectEntity(entity, el);
      const dragStart = { x: entity.x, y: entity.y };
      let moved = false;
      ox = e.clientX - entity.x;
      oy = e.clientY - entity.y;
      e.preventDefault();
      const onMouseMove = event => {
        if (!dragging) return;
        const nextX = event.clientX - ox;
        const nextY = event.clientY - oy;
        if (nextX !== entity.x || nextY !== entity.y) moved = true;
        entity.x = nextX;
        entity.y = nextY;
        el.style.left = entity.x + 'px';
        el.style.top = entity.y + 'px';
        this.drawRelations();
      };
      const onMouseUp = () => {
        if (dragging && moved) {
          this.pushUndoAction({
            type: 'moveEntity',
            entityId: entity.id,
            x: dragStart.x,
            y: dragStart.y,
          });
        }
        dragging = false;
        document.removeEventListener('mousemove', onMouseMove);
        document.removeEventListener('mouseup', onMouseUp);
      };
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
    });
    el.addEventListener('dblclick', () => {
      this.showEntityForm(entity);
    });
    this.canvas.appendChild(el);
  }
  selectEntity(entity, el) {
    this.canvas.querySelectorAll('.er-entity').forEach(e => e.classList.remove('selected'));
    this.selectedEntity = entity;
    el.classList.add('selected');
  }
  addRelation() {
    if (this.entities.length < 2) { showToast('エンティティを2つ以上追加してください'); return; }
    this.connectingFrom = null;
    showToast('接続元エンティティをクリックしてください');
    // Next click on entity will start connection
    const handler = () => {
      if (this.selectedEntity) {
        this.connectingFrom = this.selectedEntity;
        document.getElementById(this.selectedEntity.id)?.classList.add('selected');
        showToast('接続先エンティティをクリックしてください (余白クリックでキャンセル)');
        this.canvas.removeEventListener('mousedown', handler);

        // Setup dynamic line tracking
        this.activeConnectionLine = document.createElementNS('http://www.w3.org/2000/svg','line');
        this.activeConnectionLine.setAttribute('stroke','#f59e0b');
        this.activeConnectionLine.setAttribute('stroke-width','2');
        this.activeConnectionLine.setAttribute('stroke-dasharray','5,5');
        this.svg.appendChild(this.activeConnectionLine);

        const mouseMoveHandler = (e) => {
          if (!this.connectingFrom) {
            document.removeEventListener('mousemove', mouseMoveHandler);
            if (this.activeConnectionLine) {
              this.activeConnectionLine.remove();
              this.activeConnectionLine = null;
            }
            return;
          }
          const fromEl = document.getElementById(this.connectingFrom.id);
          if (!fromEl) return;
          const cr = this.canvas.getBoundingClientRect();
          const fr = fromEl.getBoundingClientRect();
          const x1 = fr.left + fr.width/2 - cr.left;
          const y1 = fr.top + fr.height/2 - cr.top;
          const x2 = e.clientX - cr.left;
          const y2 = e.clientY - cr.top;

          this.activeConnectionLine.setAttribute('x1', x1);
          this.activeConnectionLine.setAttribute('y1', y1);
          this.activeConnectionLine.setAttribute('x2', x2);
          this.activeConnectionLine.setAttribute('y2', y2);
        };
        document.addEventListener('mousemove', mouseMoveHandler);
      }
    };
    setTimeout(() => this.canvas.addEventListener('mousedown', handler), 100);
  }
  pushUndoAction(action) {
    if (this.isApplyingUndo || !action) return;
    this.undoHistory.push(action);
  }
  getEntityById(entityId) {
    return this.entities.find(entity => entity.id === entityId) || null;
  }
  removeEntityById(entityId) {
    const index = this.entities.findIndex(entity => entity.id === entityId);
    if (index < 0) return null;
    const [entity] = this.entities.splice(index, 1);
    const removedRelations = this.relations.filter(rel => rel.from === entityId || rel.to === entityId);
    this.relations = this.relations.filter(rel => rel.from !== entityId && rel.to !== entityId);
    const el = document.getElementById(entityId);
    if (el) el.remove();
    if (this.selectedEntity && this.selectedEntity.id === entityId) this.selectedEntity = null;
    if (this.connectingFrom && this.connectingFrom.id === entityId) this.connectingFrom = null;
    return { entity, removedRelations };
  }
  restoreSnapshot(snapshot) {
    if (!snapshot) return;
    this.entities = snapshot.entities.map(entity => ({ ...entity, attrs: entity.attrs.map(attr => ({ ...attr })) }));
    this.relations = snapshot.relations.map(rel => ({ ...rel }));
    this.entityIdCounter = snapshot.entityIdCounter;
    this.selectedEntity = null;
    this.connectingFrom = null;
    this.canvas.querySelectorAll('.er-entity').forEach(e => e.remove());
    this.svg.innerHTML = '';
    this.entities.forEach(entity => this.renderEntity(entity));
    this.drawRelations();
  }
  undoLastAction() {
    const action = this.undoHistory.pop();
    if (!action) {
      showToast('戻せる操作がありません');
      return;
    }

    this.isApplyingUndo = true;
    try {
      if (action.type === 'removeEntity') {
        this.removeEntityById(action.entityId);
        this.entityIdCounter = action.entityIdCounter;
        this.drawRelations();
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'moveEntity') {
        const entity = this.getEntityById(action.entityId);
        const el = entity ? document.getElementById(entity.id) : null;
        if (entity && el) {
          entity.x = action.x;
          entity.y = action.y;
          el.style.left = `${entity.x}px`;
          el.style.top = `${entity.y}px`;
          this.drawRelations();
        }
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'renameEntity' || action.type === 'updateEntity') {
        const entity = this.getEntityById(action.entityId);
        const el = entity ? document.getElementById(entity.id) : null;
        if (entity && el) {
          if (action.type === 'renameEntity') {
            entity.logicalName = action.name;
          } else {
            entity.logicalName = action.oldState.logicalName;
            entity.physicalName = action.oldState.physicalName;
            entity.attrs = action.oldState.attrs;
          }
          el.querySelector('.er-entity-header').textContent = this.viewMode === 'logical' ? entity.logicalName : entity.physicalName;
          el.querySelector('.er-entity-attrs').innerHTML = entity.attrs.map(a => `<div class="er-attr">
            ${a.pk?'<span class="attr-key">PK</span>':''}${a.fk?'<span class="attr-key" style="color:#06b6d4">FK</span>':''}
            <span>${this.escapeHtml(this.viewMode === 'logical' ? a.logicalName : a.physicalName)}</span><span class="attr-type">${a.type}</span>
          </div>`).join('');
        }
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'removeRelation') {
        this.relations = this.relations.filter(rel => !(rel.from === action.from && rel.to === action.to && rel.label === action.label));
        this.drawRelations();
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'restoreRelation') {
        this.relations.push(action.relation);
        this.drawRelations();
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'updateRelation') {
        const rel = this.relations.find(r => r.from === action.oldState.from && r.to === action.oldState.to);
        if (rel) {
          rel.label = action.oldState.label;
          this.drawRelations();
        }
        showToast('一つ戻しました');
        return;
      }

      if (action.type === 'clearAll') {
        this.restoreSnapshot(action.snapshot);
        showToast('一つ戻しました');
        return;
      }

      showToast('戻し処理に失敗しました');
    } finally {
      this.isApplyingUndo = false;
    }
  }
  drawRelations() {
    this.svg.innerHTML = `
      <defs>
        <marker id="er-arrow" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
          <polygon points="0 0,10 3.5,0 7" fill="#06b6d4"/>
        </marker>
        <marker id="crows-1-start" markerWidth="14" markerHeight="14" refX="0" refY="7" orient="auto">
          <line x1="8" y1="2" x2="8" y2="12" stroke="#06b6d4" stroke-width="2"/>
          <line x1="14" y1="2" x2="14" y2="12" stroke="#06b6d4" stroke-width="2"/>
        </marker>
        <marker id="crows-1-end" markerWidth="14" markerHeight="14" refX="14" refY="7" orient="auto">
          <line x1="6" y1="2" x2="6" y2="12" stroke="#06b6d4" stroke-width="2"/>
          <line x1="0" y1="2" x2="0" y2="12" stroke="#06b6d4" stroke-width="2"/>
        </marker>
        <marker id="crows-n-start" markerWidth="14" markerHeight="14" refX="0" refY="7" orient="auto">
          <line x1="14" y1="7" x2="0" y2="0" stroke="#06b6d4" stroke-width="2"/>
          <line x1="14" y1="7" x2="0" y2="14" stroke="#06b6d4" stroke-width="2"/>
          <line x1="0" y1="7" x2="14" y2="7" stroke="#06b6d4" stroke-width="2"/>
        </marker>
        <marker id="crows-n-end" markerWidth="14" markerHeight="14" refX="14" refY="7" orient="auto">
          <line x1="0" y1="7" x2="14" y2="0" stroke="#06b6d4" stroke-width="2"/>
          <line x1="0" y1="7" x2="14" y2="14" stroke="#06b6d4" stroke-width="2"/>
          <line x1="14" y1="7" x2="0" y2="7" stroke="#06b6d4" stroke-width="2"/>
        </marker>
      </defs>`;
      
    this.relations.forEach(rel => {
      const fromEl = document.getElementById(rel.from);
      const toEl = document.getElementById(rel.to);
      if (!fromEl || !toEl) return;
      const cr = this.canvas.getBoundingClientRect();
      const fr = fromEl.getBoundingClientRect();
      const tr = toEl.getBoundingClientRect();
      const x1 = fr.left + fr.width/2 - cr.left;
      const y1 = fr.top + fr.height/2 - cr.top;
      const x2 = tr.left + tr.width/2 - cr.left;
      const y2 = tr.top + tr.height/2 - cr.top;
      
      let startMarker = '';
      let endMarker = '';
      const lbl = rel.label.toUpperCase();
      if (lbl.includes('1:N')) {
         startMarker = 'url(#crows-1-start)'; endMarker = 'url(#crows-n-end)';
      } else if (lbl.includes('N:1')) {
         startMarker = 'url(#crows-n-start)'; endMarker = 'url(#crows-1-end)';
      } else if (lbl.includes('N:M')) {
         startMarker = 'url(#crows-n-start)'; endMarker = 'url(#crows-n-end)';
      } else if (lbl.includes('1:1')) {
         startMarker = 'url(#crows-1-start)'; endMarker = 'url(#crows-1-end)';
      } else {
         endMarker = 'url(#er-arrow)'; // default
      }

      const g = document.createElementNS('http://www.w3.org/2000/svg','g');
      g.style.cursor = 'pointer';
      
      const hitbox = document.createElementNS('http://www.w3.org/2000/svg','line');
      hitbox.setAttribute('x1',x1); hitbox.setAttribute('y1',y1);
      hitbox.setAttribute('x2',x2); hitbox.setAttribute('y2',y2);
      hitbox.setAttribute('stroke','transparent'); hitbox.setAttribute('stroke-width','15');
      g.appendChild(hitbox);

      const line = document.createElementNS('http://www.w3.org/2000/svg','line');
      line.setAttribute('x1',x1); line.setAttribute('y1',y1);
      line.setAttribute('x2',x2); line.setAttribute('y2',y2);
      line.setAttribute('stroke','#06b6d4'); line.setAttribute('stroke-width','2');
      if (startMarker) line.setAttribute('marker-start', startMarker);
      if (endMarker) line.setAttribute('marker-end', endMarker);
      line.setAttribute('opacity','0.6');
      g.appendChild(line);

      // Label
      const text = document.createElementNS('http://www.w3.org/2000/svg','text');
      text.setAttribute('x',(x1+x2)/2+8); text.setAttribute('y',(y1+y2)/2-8);
      text.setAttribute('fill','#06b6d4'); text.setAttribute('font-size','12');
      text.setAttribute('font-family','Inter,sans-serif');
      text.textContent = rel.label;
      g.appendChild(text);

      g.addEventListener('click', (e) => {
        e.stopPropagation();
        const newLabel = prompt('リレーション (例: 1:N, N:M) [空で削除]:', rel.label);
        if (newLabel !== null) {
          if (newLabel.trim() === '') {
            this.pushUndoAction({ type: 'restoreRelation', relation: { ...rel } });
            this.relations = this.relations.filter(r => r !== rel);
          } else {
            this.pushUndoAction({ type: 'updateRelation', oldState: { ...rel }, newState: { ...rel, label: newLabel } });
            rel.label = newLabel;
          }
          this.drawRelations();
        }
      });
      g.addEventListener('mouseenter', () => { line.setAttribute('opacity','1'); line.setAttribute('stroke-width','3'); });
      g.addEventListener('mouseleave', () => { line.setAttribute('opacity','0.6'); line.setAttribute('stroke-width','2'); });

      this.svg.appendChild(g);
    });
  }
  clearAll() {
    if (!confirm('E-R図をクリアします。よろしいですか？')) {
      return;
    }
    const snapshot = {
      entities: this.entities.map(entity => ({ ...entity, attrs: entity.attrs.map(attr => ({ ...attr })) })),
      relations: this.relations.map(rel => ({ ...rel })),
      entityIdCounter: this.entityIdCounter,
    };
    this.entities = []; this.relations = []; this.entityIdCounter = 0;
    this.canvas.querySelectorAll('.er-entity').forEach(e => e.remove());
    this.svg.innerHTML = '';
    this.pushUndoAction({ type: 'clearAll', snapshot });
    showToast('E-R図をクリアしました');
  }
  exportSVG() {
    showToast('SVGをエクスポートしました');
  }
}
